package zm.co.tbz.goldenleaf.ui.navigation

object Routes {
    const val SPLASH = "splash"
    const val ONBOARDING = "onboarding"
    const val PORTAL_LOGIN = "portal_login"
    const val LOGIN_2FA = "login_2fa"
    const val MAIN = "main"
    const val HOME = "home"
    const val SEARCH = "search"
    const val MENU = "menu"
    const val PROFILE = "profile"
    const val NOTIFICATIONS = "notifications"
    const val SYNC_SETTINGS = "sync_settings"
    const val CHANGE_PASSWORD = "change_password"
    const val ABOUT = "about"
    const val TERMS = "terms"
    const val PRIVACY = "privacy"
    const val GUIDELINES = "guidelines"
    const val REGISTRATION = "registration"
    const val REGISTRATION_NEW = "registration/new"
    const val REGISTRATION_LIST = "registration/list"
    const val REGISTRATION_LOCAL = "registration/local"
    const val REGISTRATION_DETAIL = "registration/detail/{localId}"
    const val REGISTRATION_EDIT = "registration/edit/{localId}"
    const val REGISTRATION_CORRECTION = "registration/correction/{localId}"
    const val REGISTRATION_CROP = "registration/crop/{localId}"
    const val GROWER_UPDATES = "grower-updates"
    const val CORRECTIONS = "corrections"
    const val INSPECTION = "inspection"
    const val MARKETING = "marketing"
    const val PERMITS = "permits"
    const val ARBITRATION = "arbitration"
    const val RENEWAL = "renewal"
    const val PLACEHOLDER = "placeholder/{title}"

    fun registrationDetail(localId: String) = "registration/detail/$localId"
    fun registrationEdit(localId: String) = "registration/edit/$localId"
    fun registrationCorrection(localId: String) = "registration/correction/$localId"
    fun registrationCrop(localId: String) = "registration/crop/$localId"
    fun placeholder(title: String) = "placeholder/$title"
}
